"use client";

import { useState } from "react";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";

const SYMPTOMS = [
  { id: "one_more", label: "Says 'just one more prompt' and means 47 more" },
  { id: "naming", label: "Has named their terminal window" },
  { id: "talking", label: "Talks to Claude more than to me" },
  { id: "dinner", label: "Lets dinner go cold while 'debugging'" },
  { id: "sleep", label: "Comes to bed at 4am smelling of keyboard" },
  { id: "phone", label: "Checks Claude on their phone during date night" },
  { id: "excuses", label: "Says 'I'm almost done' every 45 minutes for 8 hours" },
  { id: "dreams", label: "Mumbles about 'context windows' in their sleep" },
  { id: "deny", label: "Denies having a problem while having 12 tabs open" },
  { id: "relate", label: "Can no longer hold a conversation without saying 'let me think about that'" },
  { id: "budget", label: "The API bill is higher than the grocery bill" },
  { id: "weekend", label: "Cancelled weekend plans to 'ship a feature'" },
];

const SEVERITY_LABELS: Record<string, { label: string; message: string }> = {
  mild: {
    label: "Early stage",
    message: "There is still hope. Intervention recommended within 48 hours.",
  },
  moderate: {
    label: "Advanced dependency",
    message: "The patient is exhibiting significant Claude dependency. Immediate intervention required.",
  },
  severe: {
    label: "Terminal case",
    message: "We regret to inform you that your loved one is beyond conventional treatment. Consider unplugging the router.",
  },
  critical: {
    label: "Lost cause",
    message: "The person you knew is gone. In their place stands a prompt engineer. Our deepest condolences.",
  },
};

function getSeverity(count: number) {
  if (count <= 3) return "mild";
  if (count <= 6) return "moderate";
  if (count <= 9) return "severe";
  return "critical";
}

export default function InterventionPage() {
  const [name, setName] = useState("");
  const [checked, setChecked] = useState<Set<string>>(new Set());
  const [submitted, setSubmitted] = useState(false);
  const [copied, setCopied] = useState(false);

  function toggle(id: string) {
    const next = new Set(checked);
    if (next.has(id)) next.delete(id);
    else next.add(id);
    setChecked(next);
  }

  const severity = getSeverity(checked.size);
  const info = SEVERITY_LABELS[severity];
  const patientName = name.trim() || "the patient";

  const today = new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  const letterText = `CLINICAL INTERVENTION NOTICE
Claudict Recovery Center
${today}

RE: ${patientName}
DIAGNOSIS: ${info.label} (${checked.size}/${SYMPTOMS.length} symptoms confirmed)

Dear concerned party,

Following your report, we have assessed ${patientName} and identified the following symptoms:

${Array.from(checked)
  .map((id) => `- ${SYMPTOMS.find((s) => s.id === id)?.label}`)
  .join("\n")}

Clinical assessment: ${info.message}

${checked.size >= 10 ? `NOTE: At ${checked.size} confirmed symptoms, ${patientName} qualifies for our inpatient program at claudict.com. Admission is involuntary at this stage.` : `We strongly recommend enrolling ${patientName} at claudict.com for monitoring and community support.`}

This notice was generated by a concerned loved one via the Claudict Recovery Center Intervention Program.

---
claudict.com — Because someone has to care.`;

  function copyLetter() {
    navigator.clipboard.writeText(letterText);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }

  if (submitted && checked.size > 0) {
    return (
      <div className="max-w-2xl mx-auto px-4 py-12">
        <div className="text-center mb-8">
          <p className="text-xs uppercase tracking-[3px] text-accent mb-2">
            Intervention filed
          </p>
          <h1 className="font-serif text-2xl md:text-3xl text-text">
            Clinical intervention notice
          </h1>
        </div>

        <Card className="font-mono text-xs leading-relaxed whitespace-pre-wrap bg-surface-elevated p-6">
          {letterText}
        </Card>

        <div className="flex justify-center gap-3 mt-6">
          <Button onClick={copyLetter}>
            {copied ? "Copied to clipboard" : "Copy intervention notice"}
          </Button>
          <Button
            onClick={() => {
              setSubmitted(false);
              setChecked(new Set());
              setName("");
            }}
            className="bg-transparent border border-border text-muted hover:text-text hover:border-text"
          >
            File another report
          </Button>
        </div>

        <p className="text-center text-[10px] text-muted/50 mt-4 font-mono">
          Share this with your loved one. Or their employer. Or their therapist. Whoever is left.
        </p>
      </div>
    );
  }

  return (
    <div className="max-w-2xl mx-auto px-4 py-12">
      <div className="text-center mb-8 stagger-children">
        <p className="text-xs uppercase tracking-[3px] text-accent mb-2">
          Concerned partner program
        </p>
        <h1 className="font-serif text-2xl md:text-3xl text-text">
          Report a loved one
        </h1>
        <p className="text-sm text-muted mt-3 max-w-md mx-auto">
          Is someone you love showing signs of Claude dependency?
          Complete this clinical assessment and we will generate an official intervention notice.
        </p>
      </div>

      <div className="mb-6">
        <label className="text-xs text-muted font-mono block mb-1.5">
          Patient name (or GitHub handle)
        </label>
        <input
          type="text"
          value={name}
          onChange={(e) => setName(e.target.value)}
          placeholder="The person you're losing to an AI"
          className="w-full px-3 py-2 rounded-md bg-surface border border-border text-text text-sm placeholder:text-muted/40 focus:outline-none focus:border-accent"
        />
      </div>

      <div className="mb-6">
        <p className="text-xs text-muted font-mono mb-3">
          Check all symptoms that apply ({checked.size}/{SYMPTOMS.length})
        </p>
        <div className="space-y-2">
          {SYMPTOMS.map((symptom) => (
            <label
              key={symptom.id}
              className={`
                flex items-start gap-3 p-3 rounded-md border cursor-pointer transition-all
                ${checked.has(symptom.id)
                  ? "border-accent/40 bg-accent/5"
                  : "border-border hover:border-accent/20"
                }
              `}
            >
              <input
                type="checkbox"
                checked={checked.has(symptom.id)}
                onChange={() => toggle(symptom.id)}
                className="mt-0.5 accent-accent"
              />
              <span className="text-sm text-text">{symptom.label}</span>
            </label>
          ))}
        </div>
      </div>

      {checked.size > 0 && (
        <div className="mb-6 p-4 rounded-md border border-accent/30 bg-accent/5 animate-fade-in">
          <p className="text-xs font-mono text-accent font-bold uppercase tracking-wider">
            {info.label}
          </p>
          <p className="text-sm text-muted mt-1">{info.message}</p>
        </div>
      )}

      <Button
        onClick={() => setSubmitted(true)}
        disabled={checked.size === 0}
        className="w-full"
      >
        {checked.size === 0
          ? "Select at least one symptom"
          : `File intervention report (${checked.size} symptoms)`
        }
      </Button>

      <p className="text-center text-[10px] text-muted/40 mt-4 font-mono">
        No actual medical professionals were consulted. This is a cry for help, not a diagnosis.
      </p>
    </div>
  );
}
